### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by chaudhry13** [BVNetwork/SqlBlobProvider#12]
I have installed the latest version which supports cms 12 but when I run the application I get this error 

Object reference not set to an instance of an object
   at EPiCode.SqlBlobProvider.SqlBlob.OpenRead()

   at EPiCode.SqlBlobProvider.SqlBlob.OpenRead()
   at EPiServer.Web.Routing.Matching.Blobs.BlobFileInfoWrapper.CreateReadStream()
   at EPiServer.Web.Routing.Matching.Blobs.BlobFileInfoWrapper.get_Length()
   at Baaijte.Optimizely.ImageSharp.Web.Resolvers.BlobImageResolver.GetMetaDataAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by evest** [comment]
Close as old.
